// Master country list for the "Countries of the World" unlock game.
// 193 UN member states + Vatican City + Palestine = 195.
//
// `iso` is the 2-letter code used as the path/group id in assets/world-map.svg,
// so a correct guess can highlight that country on the map. The map is a
// simplified world map and doesn't include some small island nations/microstates
// (Andorra, Antigua and Barbuda, Bahrain, Barbados, Fiji, Grenada, Kiribati,
// Liechtenstein, Marshall Islands, Micronesia, Monaco, Nauru, Palau, Palestine,
// Saint Kitts and Nevis, Samoa, San Marino, Timor-Leste, Tonga, Tuvalu, Vatican
// City) — those still count for the counter/list, they just won't light up.
const COUNTRIES = [
  { name: 'Afghanistan', iso: 'af' },
  { name: 'Albania', iso: 'al' },
  { name: 'Algeria', iso: 'dz' },
  { name: 'Andorra' },
  { name: 'Angola', iso: 'ao' },
  { name: 'Antigua and Barbuda' },
  { name: 'Argentina', iso: 'ar' },
  { name: 'Armenia', iso: 'am' },
  { name: 'Australia', iso: 'au' },
  { name: 'Austria', iso: 'at' },
  { name: 'Azerbaijan', iso: 'az' },
  { name: 'Bahamas', iso: 'bs' },
  { name: 'Bahrain' },
  { name: 'Bangladesh', iso: 'bd' },
  { name: 'Barbados' },
  { name: 'Belarus', iso: 'by' },
  { name: 'Belgium', iso: 'be' },
  { name: 'Belize', iso: 'bz' },
  { name: 'Benin', iso: 'bj' },
  { name: 'Bhutan', iso: 'bt' },
  { name: 'Bolivia', iso: 'bo' },
  { name: 'Bosnia and Herzegovina', iso: 'ba', aliases: ['bosnia'] },
  { name: 'Botswana', iso: 'bw' },
  { name: 'Brazil', iso: 'br' },
  { name: 'Brunei', iso: 'bn' },
  { name: 'Bulgaria', iso: 'bg' },
  { name: 'Burkina Faso', iso: 'bf' },
  { name: 'Burundi', iso: 'bi' },
  { name: 'Cabo Verde', iso: 'cv', aliases: ['cape verde'] },
  { name: 'Cambodia', iso: 'kh' },
  { name: 'Cameroon', iso: 'cm' },
  { name: 'Canada', iso: 'ca' },
  { name: 'Central African Republic', iso: 'cf', aliases: ['car'] },
  { name: 'Chad', iso: 'td' },
  { name: 'Chile', iso: 'cl' },
  { name: 'China', iso: 'cn' },
  { name: 'Colombia', iso: 'co' },
  { name: 'Comoros', iso: 'km' },
  { name: 'Republic of the Congo', iso: 'cg', aliases: ['congo', 'congo brazzaville', 'congo-brazzaville'] },
  { name: 'Democratic Republic of the Congo', iso: 'cd', aliases: ['dr congo', 'drc', 'congo kinshasa', 'congo-kinshasa'] },
  { name: 'Costa Rica', iso: 'cr' },
  { name: 'Croatia', iso: 'hr' },
  { name: 'Cuba', iso: 'cu' },
  { name: 'Cyprus', iso: 'cy' },
  { name: 'Czechia', iso: 'cz', aliases: ['czech republic'] },
  { name: 'Denmark', iso: 'dk' },
  { name: 'Djibouti', iso: 'dj' },
  { name: 'Dominica', iso: 'dm' },
  { name: 'Dominican Republic', iso: 'do' },
  { name: 'Ecuador', iso: 'ec' },
  { name: 'Egypt', iso: 'eg' },
  { name: 'El Salvador', iso: 'sv' },
  { name: 'Equatorial Guinea', iso: 'gq' },
  { name: 'Eritrea', iso: 'er' },
  { name: 'Estonia', iso: 'ee' },
  { name: 'Eswatini', iso: 'sz', aliases: ['swaziland'] },
  { name: 'Ethiopia', iso: 'et' },
  { name: 'Fiji' },
  { name: 'Finland', iso: 'fi' },
  { name: 'France', iso: 'fr' },
  { name: 'Gabon', iso: 'ga' },
  { name: 'Gambia', iso: 'gm' },
  { name: 'Georgia', iso: 'ge' },
  { name: 'Germany', iso: 'de' },
  { name: 'Ghana', iso: 'gh' },
  { name: 'Greece', iso: 'gr' },
  { name: 'Grenada' },
  { name: 'Guatemala', iso: 'gt' },
  { name: 'Guinea', iso: 'gn' },
  { name: 'Guinea-Bissau', iso: 'gw' },
  { name: 'Guyana', iso: 'gy' },
  { name: 'Haiti', iso: 'ht' },
  { name: 'Honduras', iso: 'hn' },
  { name: 'Hungary', iso: 'hu' },
  { name: 'Iceland', iso: 'is' },
  { name: 'India', iso: 'in' },
  { name: 'Indonesia', iso: 'id' },
  { name: 'Iran', iso: 'ir' },
  { name: 'Iraq', iso: 'iq' },
  { name: 'Ireland', iso: 'ie' },
  { name: 'Israel', iso: 'il' },
  { name: 'Italy', iso: 'it' },
  { name: 'Ivory Coast', iso: 'ci', aliases: ["cote d'ivoire", 'cote divoire'] },
  { name: 'Jamaica', iso: 'jm' },
  { name: 'Japan', iso: 'jp' },
  { name: 'Jordan', iso: 'jo' },
  { name: 'Kazakhstan', iso: 'kz' },
  { name: 'Kenya', iso: 'ke' },
  { name: 'Kiribati' },
  { name: 'Kuwait', iso: 'kw' },
  { name: 'Kyrgyzstan', iso: 'kg' },
  { name: 'Laos', iso: 'la' },
  { name: 'Latvia', iso: 'lv' },
  { name: 'Lebanon', iso: 'lb' },
  { name: 'Lesotho', iso: 'ls' },
  { name: 'Liberia', iso: 'lr' },
  { name: 'Libya', iso: 'ly' },
  { name: 'Liechtenstein' },
  { name: 'Lithuania', iso: 'lt' },
  { name: 'Luxembourg', iso: 'lu' },
  { name: 'Madagascar', iso: 'mg' },
  { name: 'Malawi', iso: 'mw' },
  { name: 'Malaysia', iso: 'my' },
  { name: 'Maldives', iso: 'mv' },
  { name: 'Mali', iso: 'ml' },
  { name: 'Malta', iso: 'mt' },
  { name: 'Marshall Islands' },
  { name: 'Mauritania', iso: 'mr' },
  { name: 'Mauritius', iso: 'mu' },
  { name: 'Mexico', iso: 'mx' },
  { name: 'Micronesia', aliases: ['federated states of micronesia'] },
  { name: 'Moldova', iso: 'md' },
  { name: 'Monaco' },
  { name: 'Mongolia', iso: 'mn' },
  { name: 'Montenegro', iso: 'me' },
  { name: 'Morocco', iso: 'ma' },
  { name: 'Mozambique', iso: 'mz' },
  { name: 'Myanmar', iso: 'mm', aliases: ['burma'] },
  { name: 'Namibia', iso: 'na' },
  { name: 'Nauru' },
  { name: 'Nepal', iso: 'np' },
  { name: 'Netherlands', iso: 'nl', aliases: ['holland'] },
  { name: 'New Zealand', iso: 'nz' },
  { name: 'Nicaragua', iso: 'ni' },
  { name: 'Niger', iso: 'ne' },
  { name: 'Nigeria', iso: 'ng' },
  { name: 'North Korea', iso: 'kp' },
  { name: 'North Macedonia', iso: 'mk', aliases: ['macedonia'] },
  { name: 'Norway', iso: 'no' },
  { name: 'Oman', iso: 'om' },
  { name: 'Pakistan', iso: 'pk' },
  { name: 'Palau' },
  { name: 'Palestine', aliases: ['state of palestine', 'palestinian territories'] },
  { name: 'Panama', iso: 'pa' },
  { name: 'Papua New Guinea', iso: 'pg' },
  { name: 'Paraguay', iso: 'py' },
  { name: 'Peru', iso: 'pe' },
  { name: 'Philippines', iso: 'ph' },
  { name: 'Poland', iso: 'pl' },
  { name: 'Portugal', iso: 'pt' },
  { name: 'Qatar', iso: 'qa' },
  { name: 'Romania', iso: 'ro' },
  { name: 'Russia', iso: 'ru' },
  { name: 'Rwanda', iso: 'rw' },
  { name: 'Saint Kitts and Nevis', aliases: ['st kitts and nevis'] },
  { name: 'Saint Lucia', iso: 'lc', aliases: ['st lucia'] },
  { name: 'Saint Vincent and the Grenadines', iso: 'vc', aliases: ['st vincent and the grenadines'] },
  { name: 'Samoa' },
  { name: 'San Marino' },
  { name: 'Sao Tome and Principe', iso: 'st' },
  { name: 'Saudi Arabia', iso: 'sa' },
  { name: 'Senegal', iso: 'sn' },
  { name: 'Serbia', iso: 'rs' },
  { name: 'Seychelles', iso: 'sc' },
  { name: 'Sierra Leone', iso: 'sl' },
  { name: 'Singapore', iso: 'sg' },
  { name: 'Slovakia', iso: 'sk' },
  { name: 'Slovenia', iso: 'si' },
  { name: 'Solomon Islands', iso: 'sb' },
  { name: 'Somalia', iso: 'so' },
  { name: 'South Africa', iso: 'za' },
  { name: 'South Korea', iso: 'kr', aliases: ['korea'] },
  { name: 'South Sudan', iso: 'ss' },
  { name: 'Spain', iso: 'es' },
  { name: 'Sri Lanka', iso: 'lk' },
  { name: 'Sudan', iso: 'sd' },
  { name: 'Suriname', iso: 'sr' },
  { name: 'Sweden', iso: 'se' },
  { name: 'Switzerland', iso: 'ch' },
  { name: 'Syria', iso: 'sy' },
  { name: 'Tajikistan', iso: 'tj' },
  { name: 'Tanzania', iso: 'tz' },
  { name: 'Thailand', iso: 'th' },
  { name: 'Timor-Leste', aliases: ['east timor'] },
  { name: 'Togo', iso: 'tg' },
  { name: 'Tonga' },
  { name: 'Trinidad and Tobago', iso: 'tt' },
  { name: 'Tunisia', iso: 'tn' },
  { name: 'Turkey', iso: 'tr', aliases: ['turkiye'] },
  { name: 'Turkmenistan', iso: 'tm' },
  { name: 'Tuvalu' },
  { name: 'Uganda', iso: 'ug' },
  { name: 'Ukraine', iso: 'ua' },
  { name: 'United Arab Emirates', iso: 'ae', aliases: ['uae'] },
  { name: 'United Kingdom', iso: 'gb', aliases: ['uk', 'britain', 'great britain'] },
  { name: 'United States', iso: 'us', aliases: ['usa', 'us', 'united states of america', 'america'] },
  { name: 'Uruguay', iso: 'uy' },
  { name: 'Uzbekistan', iso: 'uz' },
  { name: 'Vanuatu', iso: 'vu' },
  { name: 'Vatican City', aliases: ['holy see', 'vatican'] },
  { name: 'Venezuela', iso: 've' },
  { name: 'Vietnam', iso: 'vn' },
  { name: 'Yemen', iso: 'ye' },
  { name: 'Zambia', iso: 'zm' },
  { name: 'Zimbabwe', iso: 'zw' }
];

function normalizeCountryStr(s) {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Build lookups once: normalized name/alias -> canonical name, and name -> iso code.
const COUNTRY_LOOKUP = new Map();
const COUNTRY_ISO = new Map();
for (const c of COUNTRIES) {
  COUNTRY_LOOKUP.set(normalizeCountryStr(c.name), c.name);
  for (const alias of c.aliases || []) {
    COUNTRY_LOOKUP.set(normalizeCountryStr(alias), c.name);
  }
  if (c.iso) COUNTRY_ISO.set(c.name, c.iso);
}

function matchCountry(input) {
  const norm = normalizeCountryStr(input);
  if (!norm) return null;
  return COUNTRY_LOOKUP.get(norm) || null;
}

const TOTAL_COUNTRIES = COUNTRIES.length;
